### ISSUE TITLE
Use helper method to get Blobs from Input fields, use readAsTextFile instead of getTextFile

### ISSUE THREAD

**Issue by danyx23** [simonh1000/file-reader#4]
One thing that is still a bit odd is the difference between getTextFile which takes a string id selector and the readAs\* functions which take the FileRef directly. Am I wrong in thinking that we could just add a function 

``` Elm
getFileRefViaIDSelector: String -> FileRef
```

or something similar and the user of the library can use that to get the File to read in one of the readAs methods? As in

``` Elm
readAsTextFile (getFileRefViaIDSelector "input0") 
```

I think something like this would be nice to make the API more orthogonal. It might also be nice if there were a way to specify which file to read if several have been selected as right now this is hardcoded to be the first in the native implementation of getTextFile. 

Or maybe readAsTextFile should return a List of FileRefs so that the user can decide if he just wants to read the first if several files have been selected or all of them. What do you think?

**Comment by simonh1000** [comment]
Interesting:
- I'll play around with the first examples again. These should (ideally, I think) be placed in a standard html form, and the button should be a submit (which might then submit the file and some other fields). That'll give me a chance to see what feels like the friendliest API for what could be our most canonical example?
- we clearly do need to embrace multi-file upload. Multi is possible from the `<input type='file' multiple>` as well as drag 'n drop. I expect I'll have some time this weekend to start looking into this - I think we will end up with `List.map readFileAsText...` rather than a `readFilesAsText` but I'm not totally sure.

**Comment by danyx23** [comment]
Sounds great. I too think that it will be something like `List.map readFileAsText`. Let me know if I can help in any way.

**Comment by simonh1000** [comment]
On reflection, I've decided to remove getTextFile altogether. When I worked through examples more, I ended up processing  the blobs immediately, and that's the key ingredient for using the Native functions directly
